### ISSUE TITLE
can't export all rows at once

### ISSUE THREAD

**Issue by lucianahanan** [ipragmatech/pods-export-csv#1]
Hi. Im testing this plugin to export pods rows into csv.  It happens that when I select all and try to export, it only exports the current displaying page, and nothing else.

I'd like to export all pages. Is it a possible task ?

thanks

**Comment by abhinav-maheshwari** [comment]
Hi. This plugin is intended to only export the selected rows and since you can select only the rows of current page, it exports those rows. To export, you can use any of following three ways. 

First, Select the option to display more rows on that page and then export. 

Second way is to install our advanced bulk action plugin. With that plugin you can move between different pages and keep selecting on every page. When you use the Bulk Action export, all the selected pages will be exported. 

Third, if you only need to export all the rows, Go to the Pods Admin and edit your Pod. Click on the Admin UI tab and select the action "Export" under Actions Available. This is best if you only need to export all rows. Our plugins are more useful when you only need some rows.
